### ISSUE TITLE
FPGA入门咨询

### ISSUE THREAD

**Issue by Shzhentao** [loykylewong/FPGA-Application-Development-and-Simulation#1]
请问使用哪款FPGA入门较为合适？

**Comment by loykylewong** [comment]
抱歉因工作原因长期未维护这个repo！
这个问题得从两方面回答，一是芯片，二是开发板。
1、芯片方面，当然是选择资料完善、开发工具成熟的大厂，目前几乎只有Xilinx（AMD）和Altera（Intel）可选。
其他厂商如Lattice、Microchip，以及近年来还有很多做FPGA的国产厂商，他们的芯片本身的制程、规模都还不错，但y1s1，在资料和开发工具方面与AI两家差距很大。这些厂商的FPGA可以尝试，但不太建议用于入门学习——注意我说的是从底层代码原创开始的深入学习，不是“快速入门培训班”式的跑demo式学习——后者嘛，怎么开心怎么来就好。
2、开发板方面，有条件的、且阅读英文技术资料无太大障碍的，当然选AI两家的原厂开发板，质量无可挑剔，但是价格很不适合个人学习入门。对个人学习入门比较友好的，可以在淘宝搜一下，有好几家国内知名的开发板厂商都很不错，有的已经被A家纳入开发板合作伙伴名录，但价格依然相对友好。他们一般都会提供很多学习案例，这些案例即使一开始不懂，也可以跑起来直观体验一下，对于提升兴趣会很有帮助——兴趣是最好的老师。注意能选择板上自带调试器的最好，不然调试器也是一笔不算小的开销。
PS，我觉得学FPGA有三个层次，从浅到深：
1、跑案例，改案例，这是最浅的层次，千万不要满足于此，无论在学界、业界都不会有太大竞争力；
2、IP集成+简单逻辑编写，这是中等的层次，需要一定（对于复杂系统甚至可以说深厚）的数字逻辑系统认知和系统设计能力，到这个层次，可以说是一个合格的FPGA应用开发者了，还可以承担一定的数字IC前端设计工作；
3、IP开发，这是最深的层次，需要自己用RTL级的硬件描述语言，从零（或者说几乎从零）开始设计、构建功能和优化性能，具备这个能力的话，配合相关应用层知识，可以胜任任何FPGA应用项目开发，以及数字IC核心功能的前端开发工作。
希望你能做到第3层，这本书也是面向有志于第3层的读者的。祝学习快乐！

**Comment by Shzhentao** [comment]
嗯呐
